import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
   const { data: tasks, refetch: refetchTasks } = api.task.getAll.useQuery();
     const createTask = api.task.create.useMutation({
    onSuccess: () => {
      void refetchTasks();
    },
  });

  const deleteTask = api.task.delete.useMutation({
    onSuccess: () => {
      void refetchTasks();
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="overflow-x-auto">
            <input
              type="text"
              placeholder="Type here"
              className="input-bordered input w-full max-w-xs"
               onKeyDown={(e) => {
            if (e.key === "Enter") {
              createTask.mutate({
                title: e.currentTarget.value,
              });
              e.currentTarget.value = "";
            }
          }}
            />

            <table className="mt-2 table">
              {/* head */}
              <thead>
                <tr>
                  <th>Title</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {tasks?.map((task, index) => (
                <tr key={`${task.id}${index}`}>
                  <td>
                    <div className="flex items-center space-x-3">
                      <div>
                        <div className="font-bold">{task.title}</div>
                      </div>
                    </div>
                  </td>
                  <th>
                    <button className="btn-xs btn  btn-error" onClick={()=> void deleteTask.mutate({ id: task.id })}>Delete</button>
                  </th>
                </tr>
                ))
                  }
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
